apiVersion: v1
entries:
  musicfeed-identity-service:
  - apiVersion: v2
    appVersion: 0.0.1.619-preview
    created: "2022-06-05T18:57:03.6011447+02:00"
    description: A Helm chart for Music Feed Identity Service.
    digest: 4e5b1c85e5ed63343574efd0657c8ca0a49703b761426595f4e441591b368c81
    name: musicfeed-identity-service
    type: application
    urls:
    - musicfeed-identity-service-0.0.1-preview-619.tgz
    version: 0.0.1-preview-619
  - apiVersion: v2
    appVersion: 0.0.1.101-preview
    created: "2022-06-05T18:57:03.6001275+02:00"
    description: A Helm chart for Music Feed Identity Service.
    digest: 88fdbdf161005edff60db325d379ccdcbafbebe076933a1cafbc365fdc7207b3
    name: musicfeed-identity-service
    type: application
    urls:
    - musicfeed-identity-service-0.0.1-preview-101.tgz
    version: 0.0.1-preview-101
generated: "2022-06-05T18:57:03.5881287+02:00"
